# Generated by Django 3.2.5 on 2023-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmenta',
            old_name='time_ordered',
            new_name='time_ordereda',
        ),
        migrations.AlterField(
            model_name='appointmenta',
            name='time',
            field=models.CharField(choices=[('2 PM', '2 PM'), ('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='M', max_length=10),
        ),
    ]
